version: '3'

services:
  web:
    build:
      context: .
    container_name: notification_service
    command: ["bash", "/notification_service/docker/run.sh"]
    volumes:
      - .:/notification_service
    ports:
      - "8000:8000"
    env_file:
      - .env-docker
    depends_on:
      - redis
      - db
      - celery_worker

  celery_worker:
    container_name: notification_service_celery_worker
    build:
      context: .
    volumes:
      - .:/notification_service
    depends_on:
      - redis
      - db
    command: celery -A notification_service worker -l INFO --pool=solo

  redis:
    image: "redis:alpine"
    container_name: notification_redis_server
    ports:
      - "6379:6379"

  db:
    image: "postgres:16"
    container_name: notification_service_db
    environment:
      POSTGRES_DB: notification_service_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    command: -p 5435
    expose:
      - 5435