# Generated by Django 5.0.1 on 2024-01-21 12:49

import timezone_field.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0002_alter_message_message_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='dispatch',
            name='timezone',
            field=timezone_field.fields.TimeZoneField(choices_display='WITH_GMT_OFFSET', default='Etc/UTC'),
        ),
    ]
